version: '3.5'

services:
  app:
    container_name: app
    image: keeper:0.1
    platform: linux/amd64
    volumes:
      - ../:/home/keeper
    ports:
      - 8080:8080
    entrypoint: "/entrypoint.sh"

  db:
    container_name: db
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=keeper
      - MYSQL_ROOT_PASSWORD=keeper
      - MYSQL_USER=keeper
      - MYSQL_PASSWORD=keeper
    ports:
      - 3306:3306